### ISSUE TITLE
feedback on item being dragged

### ISSUE THREAD

**Issue by tomatau** [samvtran/react-sortable-items#3]
Currently there is feedback on the item being dragged, but the item is also duplicated and remains in the list... I cannot find a way to give feedback about the item that remains in the list's new position on release... sure it moves but it's difficult to see it move - this limits the UX greatly.

Would be best to be able to render a different component when it is the one being dragged (such as just a simple coloured bar)... or add a class to the component in the list so it can be styled to show it's new position... currently it just jumps around and it's hard to tell what's happening with complex items.

**Comment by samvtran** [comment]
So you can do both with 0.0.4: simply style ".SortableItem.is-placeholder" and/or replace the placeholder using `getPlaceholderContent()` in your SortableItemMixin component. The latter will apply the same classes to your customized placeholder, so you can still target ".SortableItem.is-placeholder".

Hope that helps and thanks for all your suggestions!
